### ISSUE TITLE
ETA for Multiple Image selection?

### ISSUE THREAD

**Issue by Guerrix** [Yummypets/YPImagePicker#10]
First of all, Thank You!! for your great work. 

I was wondering if you have in your future improvements the multiple image selection?? Or even if there is a way that I can help with it, in my spare time 😄 

Thanks!

cc @s4cha

**Comment by s4cha** [comment]
@Guerrix thanks for reaching out !

This is definitely in our roadmap :) 
I've already looked at how we could support it and I think the only limiting factor is time :)
If you are willing to participate that would be awesome !

**Comment by cwestMobile** [comment]
Has this been added?:)

**Comment by s4cha** [comment]
@cwestMobile not yet but I'm going to take a look. I will keep you posted :)

**Comment by JustinBeBoy** [comment]
i wait it

**Comment by NikKovIos** [comment]
+1

**Comment by NikKovIos** [comment]
@s4cha How can i help you with it? I can spent some hours for making this feature.

**Comment by s4cha** [comment]
@NikKovIos I suggest we open a PR where we can start implementing multi selection and refine the related api. (I just gave you commit access so that you don't need to create a fork and we can both contribute to the branch.
I believe some forks have implemented it already so you can might inspiration there.

_Side note_ - As many of you out there I have a full time job as well and it can be hard to find the time, so please excuse if things are slower than expected 🙏 

With the crop feature now out of the way, this the main big feature on our radar :)
Whoever wants to contribute in any way is very welcome of course!

**Comment by NikKovIos** [comment]
@s4cha So, do you want me to create a branch for this feature?
I checked forks - there are no implementations of the multiple selection yet.

**Comment by s4cha** [comment]
@NikKovIos sure, feel free to create a "multipleSelection" branch :) 
You can check https://github.com/ytakzk/Fusuma which implemented it recently for inspiration.

**Comment by s4cha** [comment]
I just created a multipleSelection branch to start this feature :)

**Comment by s4cha** [comment]
Here is the associated PR/Discussion if you want to follow the api design, feel free to chime in !
https://github.com/Yummypets/YPImagePicker/pull/47#issuecomment-372020567

**Comment by NikKovIos** [comment]
Continue discussion here https://github.com/Yummypets/YPImagePicker/issues/54
