### ISSUE TITLE
Is there a way to take non-squared photos?

### ISSUE THREAD

**Issue by artemsmikh** [Yummypets/YPImagePicker#11]
I'm wondering if I can somehow took non-squared photos using the "Photo" tab. Is that possible?

**Comment by s4cha** [comment]
@artemsmikh the capture itself is actually full screen but is cropped right away using `image.cgImage?.cropping(to: rect)` 

It is not possible at the moment but it should be fairly simple to support this use case.
The pain point will be the preview I guess. Should the preview reflect the actual photo taken? (which is the case in square mode)

**Comment by artemsmikh** [comment]
@s4cha that is a thing to think about. In my opinion, yes, it should. Perhaps you could extend the preview down to the bottom buttons so that the capture button will be inside the preview (not sure if it's possible though).
But anyway, it would be great to have an option to get photos in the original size,  no matter whether the preview is squared or not.  🙂

**Comment by s4cha** [comment]
@artemsmikh I'm going to look into it I'll keep you posted :)

**Comment by s4cha** [comment]
@artemsmikh, after looking at it, I believe it might be better to keep the same UI at least for now, 4:3 sized preview kind of breaks the existing designs. A full screen approach would be weird as well since not all devices have a 4:3 ratio screen :/

The api would look like this : 

```swift
config.onlySquareImagesFromCamera = false
```
This would default default to `true` to play nice with previous versions.

Let me know if such an api would work for you and don't hesitate to share if you have suggestions or modifications.

Cheers,

**Comment by artemsmikh** [comment]
@s4cha yeah, that's great! Thank you. 😃

**Comment by s4cha** [comment]
You should be good to go as of 2.3.0 -> https://github.com/Yummypets/YPImagePicker/releases/tag/2.3.0

Cheers,

**Comment by artemsmikh** [comment]
Great, thanks!
