### ISSUE TITLE
Can not see collectionView on IPad 2 in landscape

### ISSUE THREAD

**Issue by dan-leech** [Yummypets/YPImagePicker#234]
**Describe the bug**
Can not see collectionView on IPad 2 in landscape. It is hidden by Image Crop View Container.

**To Reproduce**
1. Go to choose photo screen in landscape mode
2. See error

**Expected behavior**
Espect that Asset Zoomable view will become smaller inside it container and centered. 
Image Crop View Container takes 2/3 of screen or is 1:1 square

**Environment (please complete the following information):**
 - Device: IPad 2
 - OS: iOS9.3.5
 - Xcode Version 9.4.1
 - Swift Version e.g. 4.1

**Installation Type**
 - Manual

**Comment by s4cha** [comment]
@dan-leech Thanks for reporting this 👍 
The picker doesn't support landscape mode as we speak.
I don't know if we plan to ever support it to be honest.
If this is the case then we should probably lock portrait on our side.
Would you be able to lock portrait for your use case in the meantime ?

Cheers,

**Comment by MaximGolovlev** [comment]
Can you please tell me later what to fix when you have done. I don't have an opportunity to switch from swift 4 onto 4.2 because of Locksmith pod.

**Comment by AdieOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by Alipacman** [comment]
Hey @s4cha, I would be really happy if you would support landscape in the future, since most iPad apps are rotatable. Can't you use the widthOniPad property to have a fixed width and set the hight accordingly, then everything else should be done by auto layout?

Anyway, I would understand if you decide not to implement landscape mode, since it is some effort for a small amount of people, who build iPad apps, like me 😄

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
