### ISSUE TITLE
Photo & Video Quality Drops when selecting from Library

### ISSUE THREAD

**Issue by s4cha** [Yummypets/YPImagePicker#33]
@userdar
"As soon as i choose image from library the quality goes from 100 to 10, why do you think it's happening i'm developing some kind of social media app so image quality is important"

**Comment by s4cha** [comment]
@userdar,

Are you using the default crop to square or filters?

**Comment by s4cha** [comment]
I am checking the outputted `image.size` like so
```swift
picker.didSelectImage = { [unowned picker] img in
  print(img.size)
}
```
and have the same as the original  (3024.0 x 4032.0) in iPhone X :/

Are you sure you don't have
```swift
config.libraryTargetImageSize = .cappedTo(size: X)
```
We never know :)

**Comment by om-ha** [comment]
@s4cha @badoux 
Any followup on this? Seems like setting every occurrence of `sessionPreset` and `deliveryMode` to highest quality solves this problem partially.

It's still very evident in videos though, specially for portrait videos. In this case cropping reduces the video quality.

**Comment by s4cha** [comment]
@om-ha Thanks for the details, I'm going to take a look at it today then. Last time I tried to find the issue, I only checked for photos. l I will keep you posted :)

**Comment by om-ha** [comment]
@s4cha thanks man! :D

**Comment by om-ha** [comment]
Pretty much here are the changes that solved the problem partially (cropping videos still has a drop in quality)
- setting `videoCompression` to `AVAssetExportPresetHighestQuality`
- setting `deliveryMode` of every `exportSession` to `AVAssetExportPresetHighestQuality`
- setting `sessionPreset` to `AVCaptureSessionPresetHigh`

Found two interesting discussions regarding this issue that might help in your investigation:
- [Turning turn your UIImage/CGImage into a CIImage, and use high quality compression formats in intermediary cropping steps](https://stackoverflow.com/questions/41471046/issues-with-cropping-an-image/41477176#41477176)
- [This might be useful too](https://stackoverflow.com/questions/39121225/image-becomes-blur-when-applying-cifilter)

**Comment by s4cha** [comment]
@om-ha thanks so much for your help.

**Comment by s4cha** [comment]
By the way @om-ha are you experiencing the issue with photos as well? or only videos?

**Comment by s4cha** [comment]
@om-ha 
- `videoCompression` is already set to `AVAssetExportPresetHighestQuality` in the project
- Concerning `deliveryMode` it is applied  to`PHVideoRequestOptions` or `PHImageRequestOptions `, I don't see it on `AVAssetExportSession` objects.  
- `sessionPreset` is already set to `AVCaptureSession.Preset.high` 

I continue my research :)

**Comment by s4cha** [comment]
@om-ha silly question but are you using the latest version (2.7.x) ? I have a hard time reproducing the issue.

**Comment by om-ha** [comment]
@s4cha  thank you so much for the followup and research, hugely appreciated.
To correct my previous comments:

- Each object occurrence of `AVAssetExportSession` could have its `presetName` set to the highest i.e. `AVAssetExportPresetHighestQuality` from the constructor.
- Each object occurrence of `AVCaptureSession` could have its `sessionPreset` to the highest i.e. `AVCaptureSessionPresetHigh`
- Each object occurrence of `PHImageRequestOptions` and `PHVideoRequestOptions` could have its `deliveryMode` set to `highQualityFormat`

My apologies. I hastily stated inaccurate information, as I was grasping at straws trying to solve the video cropping quality issue.

As for cropping issue, since YPImagePicker did not have cropping for videos, we are using **VideoCropView** from **PryntTrimmerView** to achieve that. So the problem is not even from YPImagePicker, I'm continuing someone else's efforts so that fact missed me. 
But YPImagePicker (in the version we used) had some presets set to Medium quality, and some `deliveryMode` set to `fastFormat`. This negatively affected quality when selecting/cropping images I assume. Setting everything to the highest quality possible did not have any detriment performance hits, as one would assume otherwise. 

I hope this comment was helpful for the original issue of degrading quality when selecting an image from gallery.

**Comment by carmelogallo** [comment]
Same problem for me :)

**Comment by om-ha** [comment]
@cikpis  check out this [commit](https://github.com/Yummypets/YPImagePicker/pull/65) by @s4cha

**Comment by s4cha** [comment]
@om-ha 
No problem! Every bit of info you provided was very useful to pinpoint the origin of the issue. Indeed previous versions of the picker were not using the highest quality settings by default. 
Actually, even though the fix works, I am still puzzled as to why `requestImage` api doesn't return the highest quality image :/
Are you now able to use the latest version in the project you talked about?

Concerning cropping videos, thanks for sharing `VideoCropView from PryntTrimmerView`, this is something we'll address it here : https://github.com/Yummypets/YPImagePicker/issues/50

Thank you so much for your help on this !

**Comment by carmelogallo** [comment]
@om-ha when is it going to be merged?

**Comment by carmelogallo** [comment]
@s4cha when are you going to merge the pull request about image quality after zoom?

**Comment by s4cha** [comment]
@om-ha @cikpis you should be good starting in 2.8.0 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.8.0
:)

**Comment by carmelogallo** [comment]
@s4cha awesome! thanks!

**Comment by om-ha** [comment]
@s4cha Cheers for fixing the bug!

**Comment by s4cha** [comment]
@om-ha You're welcome :)

**Comment by om-ha** [comment]
@s4cha dude, thanks a lot for your hard work. My previous colleague _heavily_ modified a swift-3 version of YPImagePicker, upgrading to the latest version requires a lot of work and was out of the question. So the quality issue stayed unresolved.

Today I just went in there and used the current cropping implementation from _PHCachingImageManager+Helpers_ file -> _PHCachingImageManager_ class -> _fetchImage_ method

The differences that made the quality improves are:
1. In requestImage call, we used _aspectFit_ for the _contentMode_  instead of _aspectFill_, the latter produced a relatively better quality.
2. requestImageData should replace requestImage call altogether, along with the relevant orientation reset with it. As you deduced in this thread [here](https://github.com/Yummypets/YPImagePicker/issues/33#issuecomment-375222211). As _requestImage_ returns a representation of the image asset with inferior quality, unlike _requestImageData_.

Pure awesomeness, god bless you and the open source community. I'm glad that I at least helped a tiny little bit with my humble research in this thread, and by pointing out PryntTrimmerView for video cropping. But the hero of the day was you and the many contributors that helped build this.
