### ISSUE TITLE
in iOS 14 when user not allowed to use all photos, apple present own default image picker.

### ISSUE THREAD

**Issue by sadeghgoo** [Yummypets/YPImagePicker#578]
in iOS 14 when user not allowed to use all photos, apple present own default image picker. How can I handle that in YPImage picker

**Comment by murilxaraujo** [comment]
When user selects to allow some photos option the system will show them a picker to select the images it will expose to the app, and after that, it should show the custom picker presenting only the previously selected images. I don't think it can be changed since it is a change in the privacy feature.

**Comment by NikKovIos** [comment]
Agree with @murilxaraujo
