### ISSUE TITLE
Support circular Crop

### ISSUE THREAD

**Issue by s4cha** [Yummypets/YPImagePicker#77]
Thanks @userdar for suggesting this cool addition.

**Comment by neodave** [comment]
I am interested in something like this, but not a crop. I would like to have a circular overlay mask over a square crop to preview what an avatar image will look like. But I don't want to actually make the image a cropped circle, rather a square. That make sense? I am trying to implement it myself and will share my results if this turns out to be an actual crop

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
